
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "org-clock-hooks" "20180404.1238" "org-clock-hooks")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "org-clock-hooks-pkg.el" "org-clock-hooks.el")


 (depends-on "lotus-utils"))
