
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "org-clock-daysummary" "20171222.127" "Org clock day summary")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "org-clock-daysummary-pkg.el" "org-clock-daysummary.el")


 (depends-on "spaceline")
 (depends-on "lotus-utils"))
