
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "org-clock-in-if-not" "20180404.1239" "org-clock-in-if-not")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "org-clock-in-if-not-pkg.el" "org-clock-in-if-not.el")


 (depends-on "lotus-utils"))
