
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "org-clock-in-if-not" "20191027.2325" "org-clock-in-if-not")


(files
 "org-clock-in-if-not-pkg.el"
 "org-clock-in-if-not.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "lotus-utils"))
