
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "lotus-wrapper" "20180509.1" "lotus-wrapper")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "lotus-wrapper-pkg.el" "lotus-wrapper.el")

)
