
(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")


(package "org-clock-wrapper" "20180404.1240" "org-clock-wrapper")


(files
 "org-clock-wrapper-pkg.el"
 "org-clock-wrapper.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "lotus-utils"))
