
(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")


(package "tagging" "20190106.2009" "tagging")


(files
 "tagging-pkg.el"
 "tagging.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
