
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "org-clock-wrapper" "20180404.1240" "org-clock-wrapper")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "org-clock-wrapper-pkg.el" "org-clock-wrapper.el")


 (depends-on "lotus-utils"))
