
(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")


(package "lotus-note" "20190801.1353" "lotus-note")


(files
 "lotus-note-pkg.el"
 "lotus-note.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
