
(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")


(package "org-clock-hooks" "20180404.1238" "org-clock-hooks")


(files
 "org-clock-hooks-pkg.el"
 "org-clock-hooks.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "lotus-utils"))
