
(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")


(package "p4" "20191025.2044" "p4")


(files
 "p4-lowlevel.el"
 "p4-pkg.el"
 "vc-p4.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
