
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "pa-planner" "20191027.2325" "pa-planner")


(files
 "pa-planner-pkg.el"
 "pa-planner.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "planner-utils"))
