
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "echoserver" "20190106.1920" "echoserver")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "echoserver-pkg.el" "echoserver.el")

)
