
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "org-onchange" "20171222.128" "org-onchange")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "org-note-mail.el" "org-onchange-pkg.el" "org-onchange.el")


 (depends-on "lotus-utils")
 (depends-on "s"))
