
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "package-dev-utils-lotus" "20171222.1508" "packahe dev utils")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "package-dev-utils-lotus-pkg.el" "package-dev-utils-lotus.el")

)
