(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")

(package "org-capture+" "0.2.1" "org-capture+.")

(files "org-capture+.el"
       "org-capture+-lib.el"
       "org-capture+-helm.el"
       "org-capture+-macros.el"
       "org-capture+-helm-dynamic.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "helm")
 (depends-on "lotus-tree-manager")
 (depends-on "lotus-utils"))
