
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "emacs-panel" "20191027.2325" "emacs-panel")


(files
 "emacs-panel-pkg.el"
 "emacs-panel.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
