
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "emacs-panel" "20181227.321" "emacs-panel")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "emacs-panel-pkg.el" "emacs-panel.el")

)
