
(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")


(package "org-onchange" "20171222.128" "org-onchange")


(files
 "org-note-mail.el"
 "org-onchange-pkg.el"
 "org-onchange.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")
 (depends-on "lotus-utils")
 (depends-on "s"))
