
(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")


(package "org-clock-experimental" "20180404.1238" "org-clock-experimental")


(files
 "org-clock-experimental-pkg.el"
 "org-clock-experimental.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
