
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "lotus-schedule" "20191027.2325" "lotus-schedule")


(files
 "lotus-schedule-pkg.el"
 "lotus-schedule.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
