
(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")


(package "lotus-helm" "20190801.1352" "lotus-helm")


(files
 "lotus-helm-pkg.el"
 "lotus-helm.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
