
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "multibackup" "20171222.127" "multi backup")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "multibackup-pkg.el" "multibackup.el")

)
