
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "lotus-basic-utils" "20190103.1744" "lotus-basic-utils")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "basic-macros.el" "basic-utils.el" "lotus-basic-utils-pkg.el" "lotus-basic-utils.el")

)
