
(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")


(package "autoinsert+" "20171222.126" "auto insert+")


(files
 "autoinsert+-pkg.el"
 "autoinsert+.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
