
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "lotus-spacemacs-utils" "20191027.2325" "lotus-spacemacs-utils")


(files
 "lotus-spacemacs-utils-pkg.el"
 "lotus-spacemacs-utils.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
