;;; mujelly-theme.el --- Mujelly theme for GNU Emacs 24 (deftheme)

;; Author: Mark Tran <mark.tran@gmail.com>
;; URL: http://github.com/marktran/color-theme-mujelly
;; Package-Version: 20180214.1624
;; Package-Commit: bf724ce7806a738d2043544061e5f9bbfc56e674
;; Version: 1.2.9

;; Inspired by jellybeans: http://www.vim.org/scripts/script.php?script_id=2555.
(deftheme mujelly "The mujelly color theme")

(let ((class '((class color) (min-colors 89)))
      (mujelly-fg "#ffffff")
      (mujelly-bg (if (display-graphic-p) "#000000" nil))
      (mujelly-blue-0 "#8fbfdc")
      (mujelly-green-0 "#99ad6a")
      (mujelly-green-1 "#447799")
      (mujelly-green-2 "#a8ff60")
      (mujelly-green-3 "#75b5aa")
      (mujelly-grey-0 "#888888")
      (mujelly-grey-1 "#7f7f7f")
      (mujelly-grey-2 "#151515")
      (mujelly-grey-3 "#1c1c1c")
      (mujelly-grey-4 "#363636")
      (mujelly-grey-5 "#444444")
      (mujelly-orange-0 "#ffb964")
      (mujelly-orange-1 "#f4bf75")
      (mujelly-purple-0 "#8197bf")
      (mujelly-purple-1 "#474e90")
      (mujelly-purple-2 "#cd00cd")
      (mujelly-purple-3 "#aa759f")
      (mujelly-red-0 "#cf6a4c")
      (mujelly-red-1 "#dd0093")
      (mujelly-red-2 "#de5577")
      (mujelly-red-3 "#ff73fd")
      (mujelly-yellow-0 "#fad07a")
      (mujelly-yellow-1 "#ffff00"))

  (custom-theme-set-faces
   'mujelly
   `(default ((,class (:foreground ,mujelly-fg :background ,mujelly-bg))))
   `(alchemist-test--failed-face ((,class (:foreground ,mujelly-red-0))))
   `(alchemist-test--success-face ((,class (:foreground ,mujelly-green-0))))
   `(avy-lead-face ((,class (:foreground ,mujelly-fg :background ,mujelly-red-0))))
   `(avy-lead-face-0 ((,class (:foreground ,mujelly-fg :background ,mujelly-green-0))))
   `(bm-face ((,class (:background ,mujelly-grey-4))))
   `(company-preview-common ((,class (:foreground nil :background ,mujelly-purple-1))))
   `(company-scrollbar-bg ((,class (:background ,mujelly-grey-2))))
   `(company-scrollbar-fg ((,class (:background ,mujelly-grey-0))))
   `(company-tooltip ((,class (:foreground ,mujelly-fg :background ,mujelly-grey-2))))
   `(company-tooltip-common ((,class (:foreground ,mujelly-grey-1 :background ,mujelly-grey-2))))
   `(company-tooltip-common-selection ((,class (:foreground ,mujelly-grey-1 :background ,mujelly-purple-1))))
   `(company-tooltip-selection ((,class (:background ,mujelly-purple-1))))
   `(compilation-error ((,class (:foreground ,mujelly-red-0))))
   `(compilation-info ((,class (:foreground ,mujelly-yellow-0))))
   `(compilation-line-number ((,class (:foreground ,mujelly-grey-0))))
   `(compilation-mode-line-exit ((,class (:foreground ,mujelly-green-0))))
   `(compilation-mode-line-fail ((,class (:foreground ,mujelly-red-0))))
   `(compilation-mode-line-run ((,class (:foreground ,mujelly-yellow-0))))
   `(diredp-date-time ((,class (:foreground ,mujelly-fg))))
   `(diredp-deletion ((,class (:foreground ,mujelly-red-0 :background ,mujelly-bg))))
   `(diredp-dir-heading ((,class (:foreground ,mujelly-yellow-0 :background ,mujelly-bg))))
   `(diredp-dir-name ((,class (:foreground ,mujelly-green-2 :background ,mujelly-bg))))
   `(diredp-dir-priv ((,class (:foreground ,mujelly-green-2 :background ,mujelly-bg))))
   `(diredp-exec-priv ((,class (:foreground ,mujelly-fg :background ,mujelly-bg))))
   `(diredp-file-name ((,class (:foreground ,mujelly-fg))))
   `(diredp-file-suffix ((,class (:foreground ,mujelly-fg))))
   `(diredp-link-priv ((,class (:foreground ,mujelly-fg))))
   `(diredp-number ((,class (:foreground ,mujelly-fg))))
   `(diredp-no-priv ((,class (:foreground ,mujelly-fg :background ,mujelly-bg))))
   `(diredp-rare-priv ((,class (:foreground ,mujelly-red-0 :background ,mujelly-bg))))
   `(diredp-read-priv ((,class (:foreground ,mujelly-fg :background ,mujelly-bg))))
   `(diredp-symlink ((,class (:foreground ,mujelly-red-3))))
   `(diredp-write-priv ((,class (:foreground ,mujelly-fg :background ,mujelly-bg))))
   `(ediff-odd-diff-A ((,class (:foreground ,mujelly-red-0 :background ,mujelly-grey-2))))
   `(ediff-odd-diff-B ((,class (:foreground ,mujelly-green-0 :background ,mujelly-grey-2))))
   `(emmet-preview-output ((,class (:background ,mujelly-purple-1))))
   `(elixir-atom-face ((,class (:foreground ,mujelly-blue-0))))
   `(elixir-attribute-face ((,class (:foreground ,mujelly-red-0))))
   `(enh-ruby-op-face ((,class (:foreground ,mujelly-purple-0))))
   `(enh-ruby-regexp-delimiter-face ((,class (:foreground ,mujelly-purple-3))))
   `(erc-notice-face ((,class (:foreground ,mujelly-yellow-0))))
   `(erc-prompt-face ((,class (:foreground ,mujelly-fg))))
   `(erc-timestamp-face ((,class (:foreground ,mujelly-purple-0))))
   `(eshell-prompt ((,class (:foreground ,mujelly-red-0))))
   `(eshell-ls-directory ((,class (:weight normal :foreground ,mujelly-green-2))))
   `(eshell-ls-executable ((,class (:weight normal :foreground ,mujelly-red-0))))
   `(eshell-ls-product ((,class (:foreground ,mujelly-fg))))
   `(eshell-ls-symlink ((,class (:weight normal :foreground ,mujelly-purple-2))))
   `(flycheck-error ((,class (:background ,mujelly-grey-4))))
   `(flycheck-error-list-column-number ((,class (:foreground ,mujelly-fg))))
   `(flycheck-error-list-line-number ((,class (:foreground ,mujelly-fg))))
   `(flycheck-error-list-id ((,class (:foreground ,mujelly-fg))))
   `(flycheck-error-list-info ((,class (:foreground ,mujelly-yellow-0))))
   `(flycheck-info ((,class (:background ,mujelly-grey-4))))
   `(flycheck-warning ((,class (:background ,mujelly-grey-4))))
   `(font-lock-builtin-face ((,class (:foreground ,mujelly-blue-0))))
   `(font-lock-comment-face ((,class (:slant italic :foreground ,mujelly-grey-0))))
   `(font-lock-constant-face ((,class (:foreground ,mujelly-green-1))))
   `(font-lock-doc-face ((,class (:foreground ,mujelly-green-0))))
   `(font-lock-function-name-face ((,class (:foreground ,mujelly-yellow-0))))
   `(font-lock-keyword-face ((,class (:foreground ,mujelly-purple-0))))
   `(font-lock-preprocessor-face ((,class (:foreground ,mujelly-fg))))
   `(font-lock-string-face ((,class (:foreground ,mujelly-green-0))))
   `(font-lock-type-face ((,class (:foreground ,mujelly-orange-0))))
   `(font-lock-variable-name-face ((,class (:foreground ,mujelly-red-0))))
   `(font-lock-warning-face ((,class (:foreground ,mujelly-red-1))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,mujelly-yellow-0 :bold t))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,mujelly-red-0 :bold t))))
   `(fringe ((,class (:foreground ,mujelly-fg :background ,mujelly-bg))))
   `(git-commit-comment-file ((,class (:foreground ,mujelly-fg))))
   `(git-commit-comment-heading ((,class (:foreground ,mujelly-yellow-0))))
   `(git-commit-summary ((,class (:foreground ,mujelly-fg))))
   `(header-line ((,class (:foreground ,mujelly-fg))))
   `(helm-buffer-file ((,class (:foreground ,mujelly-fg))))
   `(helm-buffer-process ((,class (:foreground ,mujelly-yellow-0))))
   `(helm-buffer-size ((,class (:foreground ,mujelly-fg))))
   `(helm-candidate-number ((,class (:foreground ,mujelly-fg :background ,mujelly-bg))))
   `(helm-ff-directory ((,class (:foreground ,mujelly-green-2))))
   `(helm-ff-dotted-directory ((,class (:foreground ,mujelly-green-2 :background ,mujelly-bg))))
   `(helm-ff-dotted-symlink-directory ((,class (:foreground ,mujelly-green-2 :background ,mujelly-bg))))
   `(helm-ff-executable ((,class (:foreground ,mujelly-red-0))))
   `(helm-ff-file ((,class (:foreground ,mujelly-fg))))
   `(helm-ff-symlink ((,class (:foreground ,mujelly-purple-2))))
   `(helm-grep-lineno ((,class (:foreground ,mujelly-fg))))
   `(helm-match ((,class (:foreground ,mujelly-red-1 :background ,mujelly-bg))))
   `(helm-moccur-buffer ((,class (:foreground ,mujelly-yellow-0))))
   `(helm-selection ((,class (:background ,mujelly-purple-1))))
   `(helm-source-header ((,class (:foreground ,mujelly-yellow-0 :background ,mujelly-grey-3))))
   `(helm-swoop-target-line-face ((,class (:foreground ,mujelly-fg :background ,mujelly-grey-4))))
   `(helm-swoop-target-word-face ((,class (:foreground ,mujelly-red-1))))
   `(highlight ((,class (:background ,mujelly-grey-4))))
   `(highlight-indentation-face ((,class (:background ,mujelly-grey-4))))
   `(highlight-indentation-current-column-face ((,class (:background ,mujelly-grey-4))))
   `(hl-line ((,class (:background ,mujelly-grey-4))))
   `(iedit-occurrence ((,class (:foreground ,mujelly-red-1))))
   `(isearch ((,class (:foreground ,mujelly-fg :background ,mujelly-red-1))))
   `(isearch-fail ((,class (:background ,mujelly-red-1))))
   `(ido-first-match ((,class (:foreground ,mujelly-yellow-0))))
   `(ido-only-match ((,class (:foreground ,mujelly-green-0))))
   `(ido-subdir ((,class (:foreground ,mujelly-fg))))
   `(ido-virtual ((,class (:foreground ,mujelly-purple-0))))
   `(ivy-current-match ((,class (:background ,mujelly-purple-1))))
   `(ivy-minibuffer-match-face-1 ((,class (:foreground ,mujelly-orange-0))))
   `(ivy-minibuffer-match-face-2 ((,class (:foreground ,mujelly-orange-0))))
   `(ivy-minibuffer-match-face-3 ((,class (:foreground ,mujelly-orange-0))))
   `(ivy-minibuffer-match-face-4 ((,class (:foreground ,mujelly-orange-0))))
   `(js2-external-variable ((,class (:foreground ,mujelly-yellow-0))))
   `(js2-function-param ((,class (:foreground ,mujelly-fg))))
   `(lazy-highlight ((,class (:foreground ,mujelly-red-1 :background nil))))
   `(linum ((,class (:slant italic :foreground ,mujelly-grey-4))))
   `(magit-blame-heading ((,class (:foreground ,mujelly-grey-1 :background ,mujelly-grey-2))))
   `(magit-branch-local ((,class (:foreground ,mujelly-green-2))))
   `(magit-branch-remote ((,class (:foreground ,mujelly-green-2))))
   `(magit-section-heading ((,class (:foreground ,mujelly-yellow-0 :background ,mujelly-grey-2))))
   `(magit-diff-added ((,class (:foreground ,mujelly-green-0))))
   `(magit-diff-added-highlight ((,class (:foreground ,mujelly-green-0 :inherit (magit-section-highlight)))))
   `(magit-diff-context ((,class (:foreground ,mujelly-fg))))
   `(magit-diff-context-highlight ((,class (:foreground ,mujelly-fg :inherit (magit-section-highlight)))))
   `(magit-diff-file-heading ((,class (:weight normal :foreground ,mujelly-fg :background ,mujelly-bg))))
   `(magit-diff-file-heading-highlight ((,class (:weight normal :foreground ,mujelly-fg :background ,mujelly-grey-2))))
   `(magit-diff-hunk-heading ((,class (:foreground ,mujelly-yellow-0 :background ,mujelly-grey-2))))
   `(magit-diff-hunk-heading-highlight ((,class (:foreground ,mujelly-yellow-0 :background ,mujelly-grey-3))))
   `(magit-diff-lines-heading ((,class (:foreground ,mujelly-fg :background ,mujelly-purple-1))))
   `(magit-diff-removed ((,class (:foreground ,mujelly-red-0))))
   `(magit-diff-removed-highlight ((,class (:foreground ,mujelly-red-0 :inherit (magit-section-highlight)))))
   `(magit-diffstat-added ((,class (:foreground ,mujelly-green-0))))
   `(magit-diffstat-removed ((,class (:foreground ,mujelly-red-0))))
   `(magit-hash ((,class (:foreground ,mujelly-red-0))))
   `(magit-log-author ((,class (:foreground ,mujelly-yellow-0))))
   `(magit-mode-line-process ((,class (:foreground ,mujelly-yellow-0))))
   `(magit-mode-line-process-error ((,class (:foreground ,mujelly-red-0))))
   `(magit-popup-argument ((,class (:foreground ,mujelly-red-0))))
   `(magit-popup-disabled-argument ((,class (:foreground ,mujelly-grey-0))))
   `(magit-section-highlight ((,class (:background ,mujelly-grey-2))))
   `(match ((,class (:background ,mujelly-red-1))))
   `(minibuffer-prompt ((,class (:foreground ,mujelly-fg))))
   `(mmm-default-submode-face ((,class (:background ,mujelly-bg))))
   `(mode-line ((,class (:foreground ,mujelly-fg :background nil))))
   `(mode-line-inactive ((,class (:foreground ,mujelly-grey-4 :background nil))))
   `(org-checkbox ((,class (:foreground ,mujelly-green-0))))
   `(org-date ((,class (:foreground ,mujelly-grey-0))))
   `(org-document-info-keyword ((,class (:foreground ,mujelly-yellow-0))))
   `(org-document-title ((,class (:foreground ,mujelly-yellow-0))))
   `(org-done ((,class (:foreground ,mujelly-green-2))))
   `(org-level-1 ((,class (:foreground ,mujelly-red-2))))
   `(org-level-2 ((,class (:foreground ,mujelly-yellow-0))))
   `(org-level-3 ((,class (:foreground ,mujelly-green-1))))
   `(org-level-4 ((,class (:foreground ,mujelly-orange-0))))
   `(org-level-5 ((,class (:foreground ,mujelly-purple-3))))
   `(org-level-6 ((,class (:foreground ,mujelly-red-0))))
   `(org-level-7 ((,class (:foreground ,mujelly-blue-0))))
   `(org-level-8 ((,class (:foreground ,mujelly-green-0))))
   `(org-link ((,class (:foreground ,mujelly-blue-0))))
   `(org-meta-line ((,class (:foreground ,mujelly-grey-0))))
   `(org-special-keyword ((,class (:foreground ,mujelly-purple-0))))
   `(org-todo ((,class (:foreground ,mujelly-red-3))))
   `(region ((,class (:background ,mujelly-purple-1))))
   `(shm-current-face ((,class (:background ,mujelly-grey-4))))
   `(shm-quarantine-face ((,class (:background ,mujelly-red-1))))
   `(smerge-markers ((,class (:foreground ,mujelly-yellow-0 :background ,mujelly-grey-2))))
   `(smerge-mine ((,class (:foreground ,mujelly-fg :background ,mujelly-purple-3))))
   `(smerge-other ((,class (:foreground ,mujelly-fg :background ,mujelly-green-1))))
   `(smerge-refined-change ((,class (:foreground ,mujelly-green-0))))
   `(sp-pair-overlay-face ((,class (:background ,mujelly-grey-4))))
   `(sp-show-pair-match-face ((,class (:background ,mujelly-grey-5))))
   `(swiper-match-face-1 ((,class (:foreground ,mujelly-red-1))))
   `(swiper-match-face-2 ((,class (:foreground ,mujelly-red-1))))
   `(swiper-match-face-3 ((,class (:foreground ,mujelly-red-1))))
   `(swiper-match-face-4 ((,class (:foreground ,mujelly-red-1))))
   `(trailing-whitespace ((,class (:background ,mujelly-red-1))))
   `(warning ((,class (:foreground ,mujelly-orange-0))))
   `(web-mode-builtin-face ((,class (:foreground ,mujelly-blue-0))))
   `(web-mode-constant-face ((,class (:foreground ,mujelly-purple-0))))
   `(web-mode-css-at-rule-face ((,class (:foreground ,mujelly-blue-0))))
   `(web-mode-css-function-face ((,class (:foreground ,mujelly-orange-0))))
   `(web-mode-css-property-name-face ((,class (:foreground ,mujelly-green-3))))
   `(web-mode-css-selector-face ((,class (:foreground ,mujelly-yellow-0))))
   `(web-mode-html-attr-name-face ((,class (:foreground ,mujelly-purple-0))))
   `(web-mode-html-tag-face ((,class (:foreground ,mujelly-fg))))
   `(web-mode-symbol-face ((,class (:foreground ,mujelly-green-1))))
   `(which-key-group-description-face ((,class (:foreground ,mujelly-grey-0))))
   `(which-key-key-face ((,class (:foreground ,mujelly-green-0))))
   `(whitespace-trailing ((,class (:background ,mujelly-red-1))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'mujelly)

;;; mujelly-theme.el ends here
