
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "rcs-backup" "20191027.2325" "rcs backup")


(files
 "rcs-backup-pkg.el"
 "rcs-backup.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
