
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "lotus-crypt-utils" "20191027.2325" "lotus-crypt-utils")


(files
 "lotus-crypt-utils-pkg.el"
 "lotus-crypt-utils.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
