
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "copywithoutsel" "20190106.1919" "copywithoutsel")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "copywithoutsel-pkg.el" "copywithoutsel.el")

)
