
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "rcs-backup" "20171222.129" "rcs backup")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "rcs-backup-pkg.el" "rcs-backup.el")

)
