
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "org-clock-check" "20191027.2325" "org-clock-check")


(files
 "org-clock-check-pkg.el"
 "org-clock-check.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
