 (source gnu)
(source melpa)

(package-file "lotus-utils.el")

(files "lotus-idle-utils.el" "lotus-misc-utils.el" "lotus-utils-debug.el" "lotus-utils-pkg.el" "lotus-utils.el" "org-clock-utils-lotus.el" "org-misc-utils-lotus.el" "timer-utils-lotus.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
