
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "lotus-annotate" "20191027.2325" "lotus-annotate")


(files
 "lotus-annotate-pkg.el"
 "lotus-annotate.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
