
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "org-scahachua" "20191027.2325" "org-scahachua")


(files
 "org-sachachua.el"
 "org-scahachua-pkg.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
