
(source gnu)
(source melpa)
(source local \"~/.xemacs/elpa/upload\")


(package "org-scahachua" "20171222.129" "org-scahachua")


(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock")(files 
 "org-sachachua.el" "org-scahachua-pkg.el")

)
