
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "ff-relativedir" "20191027.2325" "ff-relativedir")


(files
 "ff-relativedir-pkg.el"
 "ff-relativedir.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
