
(source gnu)
(source melpa)
(source marmalade)
(source org)
(source local "~/.xemacs/elpa/upload")


(package "project-buffer-file" "20191027.2325" "project-buffer-file")


(files
 "project-buffer-file-pkg.el"
 "project-buffer-file.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
