
(source gnu)
(source melpa)
(source local "~/.xemacs/elpa/upload")


(package "iswitchb-fc" "20190106.1922" "iswitchb-fc")


(files
 "iswitchb-fc-pkg.el"
 "iswitchb-fc.el")

(development
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
